volumes:
  dbdata:
    driver: local
services:
  cache:
    image: busybox
    tty: true
    volumes:
      - /bundler_cache
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: mysql
      DB_PASSWORD: password
      DB_USER: root
      DB_PORT: 3306
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    volumes_from:
      - cache
